// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIuOeJSE9QGIXRzC-OjBGqIX51evSybHA',
    appId: '1:131967254697:web:fa14686a42fd9f490f29b8',
    messagingSenderId: '131967254697',
    projectId: 'hospital-7cd36',
    authDomain: 'hospital-7cd36.firebaseapp.com',
    storageBucket: 'hospital-7cd36.firebasestorage.app',
    measurementId: 'G-FCPV1LW84C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIbTZ7ilWtbNGoNjZs2o45knmEwI2ZQbg',
    appId: '1:131967254697:android:4b57dfdb861f992e0f29b8',
    messagingSenderId: '131967254697',
    projectId: 'hospital-7cd36',
    storageBucket: 'hospital-7cd36.firebasestorage.app',
  );
}
